/* global Request, URL */

import app from '../../storybook-server/index.js';
import { handle } from 'hono/vercel';
// Generated by ../../scripts/generate-vercel-trace-hints.mjs during `yarn build`;
// ships the packages the render server resolves through Vite at runtime.
import './_vercel-trace-hints.js';

const renderServer = handle(app);

// Method exports (not a default export) make Vercel's Node runtime invoke
// this with the web-standard signature — `request` is a fetch Request with an
// absolute URL, which `handle(app)` from hono/vercel expects.
function handler(request) {
  const url = new URL(request.url);

  url.pathname = url.pathname.replace(/^\/api\/storybook-astro/, '') || '/';

  return renderServer(new Request(url, request));
}

export const GET = handler;
export const POST = handler;
export const OPTIONS = handler;

/* Trace hints: the render runtime resolves these through createRequire() and
   Vite SSR at runtime, which Vercel's file tracer cannot see — without the
   literal imports below they are left out of the function bundle. This
   function is never called. */
export async function __nftTraceHints() {
  // Platform-native binaries hide behind conditional requires (vite ->
  // rollup/esbuild); list every arch the function might run on — variants
  // not installed at trace time only produce warnings.
  await import('@rollup/rollup-linux-arm64-gnu');
  await import('@rollup/rollup-linux-x64-gnu');
  await import('@rolldown/binding-linux-arm64-gnu');
  await import('@rolldown/binding-linux-x64-gnu');
  await import('@oxc-parser/binding-linux-arm64-gnu');
  await import('@oxc-parser/binding-linux-x64-gnu');
  await import('@oxc-resolver/binding-linux-arm64-gnu');
  await import('@oxc-resolver/binding-linux-x64-gnu');
  await import('@esbuild/linux-arm64');
  await import('@esbuild/linux-x64');
  await import('astro');
  await import('astro/config');
  await import('@astrojs/preact');
  await import('preact');
  await import('preact-render-to-string');
  await import('msw/node');
}
